name: Label issues
on:
  issues:
    types:
        - reopened
        - opened
jobs:
  labels_issues:
    runs-on: macos-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
